from lz import *
from easydict import EasyDict

cfgs = [
    EasyDict(dict(
        lr=3e-4*0.1*0.5,
        logs_dir='tribranch.per.batch',
        arch='resnet50',
        dataset='cuhk03',
        dataset_val='cuhk03',
        batch_size=80, print_freq=1,
        gpu=range(2),
        branchs=0,
        branch_dim=64,
        global_dim=1024,
        num_classes=128,
        resume='work.long/fuck.all.data.long.cont3/checkpoint.164.pth',
        evaluate=False,
        log_at=np.concatenate([
            # range(10, 100, 49),
            # range(100, 150, 19),
            # range(155, 165, 1),
            range(165)
        ]),
        epochs=165,
        pin_mem=True,
    )),

]

base = EasyDict(
    dict(
        retrain=False,
        pretrained=True,
        hard_examples=True,
        dbg=False,
        data_dir='/home/xinglu/.torch/data',
        restart=True,
        workers=8, split=0, height=256, width=128, combine_trainval=True,
        num_instances=4,
        # model
        evaluate=False,
        dropout=0,  # 0.5
        # loss
        margin=0.5,
        # optimizer

        lr=3e-4,

        # steps=[150, 200, 210],
        # epochs=220,
        # log_at=np.concatenate([
        #     range(0, 150, 9),
        #     range(150, 200, 5),
        #     range(200, 220, 1)
        # ]),
        steps=[100, 150, 160],
        epochs=165,
        log_at=np.concatenate([
            range(0, 100, 49),
            range(100, 150, 19),
            range(155, 165, 1),
        ]),

        weight_decay=5e-4,
        resume='',
        start_save=0,
        seed=1, print_freq=5, dist_metric='euclidean',

        branchs=0,
        branch_dim=64,
        global_dim=1024,
        num_classes=128,

        loss='triplet',
        mode='hard',
        gpu=[0, ],
        pin_mem=True,
        log_start=False,
        log_middle=True,
        freeze='',
        # tuning
        dataset='market1501',
        dataset_val='market1501',
        batch_size=100,
        logs_dir='',
        arch='resnet50',
        embed="concat",
        optimizer='adam',
        normalize=True,
        decay=0.1,
        export_config=False,
        need_second=True,
    )
)

for k, v in enumerate(cfgs):
    v = dict_update(base, v)
    cfgs[k] = EasyDict(v)


def format_cfg(cfg):
    if cfg.gpu is not None:
        cfg.pin_mem = True
        cfg.workers = 0
    else:
        cfg.pin_mem = False
        cfg.workers = 0


if __name__ == '__main__':
    # print(cfgs)
    for cfg in cfgs:
        print(cfg.logs_dir)

# edict(
#     logs_dir='se.unet.deform',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEUnetDeformBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, num_deform=1,
# ),

# edict(
#     logs_dir='sedeform.1.lr_mult.0',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEDeformBottleneck',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, num_deform=1, lr_mult=0,
# ),
# edict(
#     logs_dir='sedeform.1',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEDeformBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, num_deform=1,
# ),

# edict(
#     logs_dir='att_res',
#     arch='resnet50', block_name='AttResBottleneck', block_name2='AttResBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1,
#     # cls_pretrain=True,
# ),
#
# edict(
#     logs_dir='res.basic.scratch',
#     arch='resnet50', block_name='BasicBlock', block_name2='BasicBlock',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8, dataset_mode='combine', dropout=0,
#     cls_weight=0, tri_weight=1, random_ratio=1,
#     cls_pretrain=True,
# ),
#
# edict(
#     logs_dir='rir',
#     arch='resnet50', block_name='RIRBasicBlock', block_name2='RIRBasicBlock',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8, dataset_mode='combine', dropout=0,
#     cls_weight=0, tri_weight=1, random_ratio=1,
#     cls_pretrain=True,
# ),
#
# edict(
#     logs_dir='serir',
#     arch='resnet50', block_name='SERIRBasicBlock', block_name2='SERIRBasicBlock', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8, dataset_mode='combine', dropout=0,
#     cls_weight=0, tri_weight=1, random_ratio=1,
#     cls_pretrain=True,
# ),


# edict(
#     logs_dir='cuhk01.res',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='cuhk01', dataset_val='cuhk01',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion=None,
# ),
# edict(
#     logs_dir='cuhk01.se.concat',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cuhk01', dataset_val='cuhk01',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0.35,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion='concat',
# ),
# edict(
#     logs_dir='cuhk01.res.dop',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='cuhk01', dataset_val='cuhk01',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5, fusion=None,
# ),

# edict(
#     logs_dir='dukemtmc.res',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='dukemtmc', dataset_val='dukemtmc',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion=None,
# ),
# edict(
#     logs_dir='dukemtmc.se.concat',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='dukemtmc', dataset_val='dukemtmc',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0.35,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion='concat',
# ),
# edict(
#     logs_dir='dukemtmc.res.dop',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='dukemtmc', dataset_val='dukemtmc',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5, fusion=None,
# ),

# edict(
#     logs_dir='viper.res',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='viper', dataset_val='viper',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion=None,
# ),
# edict(
#     logs_dir='viper.se.concat',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='viper', dataset_val='viper',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0.35,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion='concat',
# ),
# edict(
#     logs_dir='viper.res.dop',
#     arch='resnet50', block_name='Bottleneck', block_name2='Bottleneck',
#     dataset='viper', dataset_val='viper',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5, fusion=None,
# ),

# edict(
#     logs_dir='senet.sum.new_avg',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion='sum',
# ),
# edict(
#     logs_dir='senet.concat.drop.0.35',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0.35,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, fusion='concat',
# ),
# edict(
#     logs_dir='senet',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1,
# ),

# edict(
#     logs_dir='senet.init_senet.dop.0.5.cdm',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cdm',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=0,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5,
# ),
# edict(
#     logs_dir='senet.init_senet.dop.0.5.cdm.worker8.longer.2',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cdm',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[80, 120], epochs=125,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5,
# ),

# edict(
#     logs_dir='senet.init_senet.dop.0.5.cdm.worker8',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cdm',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.5,
# ),

# edict(
#     logs_dir='senet.init_senet.cdm.worker8',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck',
#     dataset='cdm',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1,
# ),

# edict(
#     logs_dir='unet.deform',
#     arch='resnet50', block_name='SEBottleneck', block_name2='UnetDeformBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1, num_deform=1,
# ),

# edict(
#     logs_dir='senet.init_senet.dop.rand.0.25.worker8',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.25,
# ),

# edict(
#     logs_dir='senet.init_senet.dop.worker8',
#     arch='resnet50', block_name='SEBottleneck', block_name2='SEBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=0.25,
# ),

# edict(
#     logs_dir='deform.3.init_zero.lr_mult.0.2',
#     arch='resnet50', block_name='Bottleneck', block_name2='DeformBottleneck', dataset='cuhk03',
#     lr=3e-4, margin=0.5, area=(0.85, 1),
#     dataset_val='cuhk03', batch_size=128, num_instances=4, gpu=range(1), num_classes=128,
#     steps=[40, 60], epochs=65,
#     workers=8,
#     dataset_mode='combine',
#     dropout=0,
#     cls_weight=0, tri_weight=1,
#     random_ratio=1,
#     num_deform=3
# ),